apiVersion: v2
name: edc-provider
description: EDC Provider Helm chart for Kubernetes for Catena-X


# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 1.0.0

dependencies:
  - name: edc-dataplane
    repository: https://catenax-ng.github.io/product-edc
    version: 0.3.0
  - name: edc-controlplane
    repository: https://catenax-ng.github.io/product-edc
    version: 0.3.0
  - name: postgresql
    repository: https://charts.bitnami.com/bitnami
    version: 12.1.3
