name: "Eclipse DASH IP Check"

on:
  workflow_dispatch: # Trigger manually
  push:
    branches: main
    paths-ignore:
      - '**/*.md'
      - '**/*.txt'
  pull_request:
    branches: main
    paths:
      - '**/pom.xml'
      - 'pom.xml'
      - '**/package.json'
      - '**/yarn.lock'


jobs:
  build-frontend:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3

      - name: IP dependency check with eclipse dash tool
        run: cd frontend && npm run dependencies:generate
        shell: bash

      - name: upload results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          path: DEPENDENCIES_FRONTEND

  build-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build with Maven and check dependencies
        run: |
          cd tx-backend
          mvn --batch-mode --update-snapshots verify -Ddash.summary=../DEPENDENCIES_BACKEND -DskipTests -Pdependency-check -Ddash.fail=true

      - name: upload results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          path: DEPENDENCIES_BACKEND
