name: "Spotbugs bug detection"

on:
  push:
    branches: main
    paths-ignore:
      - '**/*.md'
      - '**/*.txt'
      - 'tx-backend/openapi/**'
      - 'tx-docs/**'
  pull_request:
    branches: main
    paths-ignore:
      - '**/*.md'
      - '**/*.txt'
      - 'tx-backend/openapi/**'
      - 'tx-docs/**'
  schedule:
    - cron: '0 0 * * *' # Once a day

jobs:
  analyze:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: tx-backend
    permissions:
      actions: read
      contents: read

    name: spotbugs-check
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: run maven spotbugs plugin
        run: mvn clean package -DskipTests=true spotbugs:check
